Fix breaking test / adapt to Rails 6.1
This change resolves the following error:
```
  1) Api::V2::PlansController OAuth (authorization_code grant type) — on behalf of a user GET /api/v2/plans (index) a valid API token is included returns the expected plans
     Failure/Error: Role.where(plan_id: inactive_plan.id, user_id: @user.id).update!(active: false)

     NoMethodError:
       undefined method `update!' for #<ActiveRecord::Relation []>
       Did you mean?  update
     # ./spec/requests/api/v2/plans_controller_spec.rb:94:in `block (5 levels) in <top (required)>'
```