Fix danger workflow
The changes implemented via this commit address the following GitHub workflow error:

```
Run gem install bundler -v 2.4
Successfully installed bundler-2.4.0
1 gem installed
[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local without 'pgsql rollbar aws'`, and stop using this flag
Your Ruby version is 3.1.6, but your Gemfile specified 3.1.4
Error: Process completed with exit code 18.
```