Disable offence-related Cops from Ruby 3.1.4 bump
Prior to this commit, the Rubocop-related GitHub action was failing with the following (https://github.com/portagenetwork/roadmap/actions/runs/9618541179/job/26532655790):
```
577 files inspected, 805 offenses detected, 805 offenses autocorrectable
Error: Process completed with exit code 1.
```

These offences are due to the bump from Ruby 3.0 to Ruby 3.1.
This commit disables the Cops corresponding to these offences. (Note: They are all "Style"-type offences)